[package]
name = "cage"
version = "0.1.0"
edition = "2018"
default-run = "cage"
authors = ["Hugues GUILLEUS <ghugues@netc.fr>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer-runtime = "0.17.1"
bincode = "1.3.3"
